name: Âu Gia Chân 6.1.118 Android 15 Nhân OKI Chung

env:
  TZ: Asia/Shanghai # Múi giờ: Châu Á/Thượng Hải
  CPU: 'sm8650' # Bộ xử lý: sm8650
  FEIL: 'oppo+oplus+realme' # Các thương hiệu: OPPO, OPlus, Realme
  ANDROID_VERSION: 'android14' # Phiên bản Android: Android 14
  KERNEL_VERSION: '6.1' # Phiên bản nhân: 6.1
  KERNEL_NAME: 'android14-11-o-gca13bffobf09' # Tên nhân: android14-11-o-gca13bffobf09
  KERNELSU_VARIANT: 'SukiSU-Ultra' # Biến thể KernelSU: SukiSU-Ultra
  KERNELSU_BRANCH: 'susfs-main' # Nhánh KernelSU: susfs-main

on:
  workflow_dispatch: # Kích hoạt quy trình làm việc theo yêu cầu
  # Bỏ ghi chú đoạn mã dưới đây để bật biên dịch định kỳ hàng ngày
#  schedule:
#    - cron: '0 23 * * *'  # Thời gian UTC 23:00 (7:00 sáng giờ Bắc Kinh ngày hôm sau)
    inputs:
      hook_method:
        description: Chế độ hook (thường sử dụng manual, chỉ cần kprobes trong một số trường hợp cần chuyển đổi chế độ sus su)
        required: true # Bắt buộc
        type: choice # Loại: lựa chọn
        default: 'manual' # Mặc định: manual
        options:
          - 'manual'
          - 'kprobes'
      lz4k_enable:
        description: 'Có cài đặt bản vá LZ4KD không'
        required: true
        type: choice
        default: 'false' # Mặc định: không
        options:
          - 'true' # Có
          - 'false' # Không
      lz4_enable:
        description: 'Có cài đặt bản vá lz4 + zstd không'
        required: true
        type: choice
        default: 'true' # Mặc định: có
        options:
          - 'true'
          - 'false'
      bbr_enable:
        description: "Có kích hoạt thuật toán BBR (tối ưu hóa dữ liệu đường lên, không quá quan trọng với sử dụng hàng ngày trên điện thoại, thậm chí có thể gây giảm hiệu suất; false: tắt, true: chỉ thêm thuật toán, default: đặt làm mặc định)"
        required: true
        type: choice
        default: 'false'
        options:
          - 'false'
          - 'true'
          - 'default'
      ssg_enable:
        description: 'Có kích hoạt bộ lập lịch IO SSG của Samsung không'
        required: true
        type: choice
        default: 'true'
        options:
          - 'true'
          - 'false'
      scx_enable:
        description: 'Có cài đặt trình điều khiển nhân Fengchi (chưa hoàn thành) không'
        required: true
        type: choice
        default: 'false'
        options:
          - 'true'
          - 'false'
      kernel_suffix:
        description: 'Hậu tố nhân (để trống mặc định, không thêm dấu gạch nối ở đầu)'
        required: false
        type: string
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest # Chạy trên môi trường Ubuntu mới nhất
    outputs:
      ksuver: ${{ steps.ksu_version.outputs.ksuver }} # Đầu ra phiên bản KernelSU
    steps:
      - name: Tối đa hóa không gian xây dựng
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192 # Dung lượng dự trữ gốc: 8192MB
          temp-reserve-mb: 2048 # Dung lượng dự trữ tạm thời: 2048MB
          swap-size-mb: 8192 # Dung lượng bộ nhớ swap: 8192MB
          remove-dotnet: 'true' # Xóa .NET
          remove-android: 'true' # Xóa Android
          remove-haskell: 'true' # Xóa Haskell
          remove-codeql: 'true' # Xóa CodeQL

      - name: Cài đặt và cấu hình các phụ thuộc môi trường
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt-get install curl bison flex make binutils dwarves git lld pahole zip perl make gcc python3 python-is-python3 bc libssl-dev libelf-dev -y
          sudo rm -rf ./llvm.sh
          sudo wget https://apt.llvm.org/llvm.sh
          sudo chmod +x llvm.sh
          sudo ./llvm.sh 20 all

      - name: Khởi tạo kho mã nguồn
        run: |
          rm -rf kernel_workspace && mkdir kernel_workspace && cd kernel_workspace
          echo "Đang sao chép kho mã nguồn..."
          git clone --depth=1 https://github.com/cctv18/android_kernel_common_oneplus_sm8650 -b oneplus/sm8650_v_15.0.0_oneplus12_6.1.118 common
          echo "Đang xóa bảo vệ ABI & xóa hậu tố dirty..."
          rm common/android/abi_gki_protected_exports_* || true
          for f in common/scripts/setlocalversion; do
            sed -i 's/ -dirty//g' "$f"
            sed -i '$i res=$(echo "$res" | sed '\''s/-dirty//g'\'')' "$f"
          done

      - name: Thêm SukiSU-Ultra
        id: ksu_version
        run: |
          cd kernel_workspace
          curl -LSs "https://raw.githubusercontent.com/ShirkNeko/SukiSU-Ultra/refs/heads/main/kernel/setup.sh" | bash -s susfs-main
          cd ./KernelSU
          KSU_VERSION=$(expr $(/usr/bin/git rev-list --count main) "+" 10700)
          echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
          echo "ksuver=$KSU_VERSION" >> $GITHUB_OUTPUT
          export KSU_VERSION=$KSU_VERSION
          sed -i "s/DKSU_VERSION=12800/DKSU_VERSION=$KSU_VERSION/" kernel/Makefile

      - name: Áp dụng bản vá SukiSU-Ultra & SUSFS
        run: |
          cd kernel_workspace
          git clone https://github.com/ShirkNeko/susfs4ksu.git -b gki-${{ env.ANDROID_VERSION }}-${{ env.KERNEL_VERSION }}
          git clone https://github.com/ShirkNeko/SukiSU_patch.git
          cp ./susfs4ksu/kernel_patches/50_add_susfs_in_gki-${{ env.ANDROID_VERSION }}-${{ env.KERNEL_VERSION }}.patch ./common/
          cp ./susfs4ksu/kernel_patches/fs/* ./common/fs/
          cp ./susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/
          cp ./SukiSU_patch/hooks/syscall_hooks.patch ./common/
          cd ./common
          patch -p1 < 50_add_susfs_in_gki-${{ env.ANDROID_VERSION }}-${{ env.KERNEL_VERSION }}.patch || true
          patch -p1 < syscall_hooks.patch || true
          
      - name: Áp dụng bản vá lz4 1.10.0 & zstd 1.5.7
        run: |
          if [ "${{ github.event.inputs.lz4_enable }}" == "true" ]; then
            echo "Đang thêm bản vá lz4 1.10.0 & zstd 1.5.7…"
            cd kernel_workspace
            git clone https://github.com/cctv18/oppo_oplus_realme_sm8650.git
            cp ./oppo_oplus_realme_sm8650/zram_patch/001-lz4.patch ./common/
            cp ./oppo_oplus_realme_sm8650/zram_patch/lz4armv8.S ./common/lib
            cp ./oppo_oplus_realme_sm8650/zram_patch/002-zstd.patch ./common/
            cd ./common
            git apply -p1 < 001-lz4.patch || true
            patch -p1 < 002-zstd.patch || true
          fi

      - name: Áp dụng bản vá Hide Stuff
        run: |
          cd kernel_workspace/common
          cp ../SukiSU_patch/69_hide_stuff.patch ./
          patch -p1 < 69_hide_stuff.patch

      - name: Áp dụng bản vá lz4kd
        run: |
          if [[ "${{ github.event.inputs.lz4k_enable }}" == "true" ]]; then
            echo "Đang thêm bản vá lz4kd…"
            cd kernel_workspace/common
            cp -r ../SukiSU_patch/other/zram/lz4k/include/linux/* ./include/linux/
            cp -r ../SukiSU_patch/other/zram/lz4k/lib/* ./lib
            cp -r ../SukiSU_patch/other/zram/lz4k/crypto/* ./crypto
            cp ../SukiSU_patch/other/zram/zram_patch/${{ env.KERNEL_VERSION }}/lz4kd.patch ./
            patch -p1 -F 3 < lz4kd.patch || true
          fi
          
      - name: Thêm cấu hình SukiSU-Ultra & SUSFS
        run: |
          cd kernel_workspace
          echo "CONFIG_KSU=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KPM=y" >> ./common/arch/arm64/configs/gki_defconfig
          if [ "${{ github.event.inputs.hook_method }}" == "kprobes" ]; then
            echo "Đang bật hook kprobes..."
            echo "CONFIG_KSU_SUSFS_SUS_SU=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_KSU_MANUAL_HOOK=n" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_KSU_KPROBES_HOOK=y" >> ./common/arch/arm64/configs/gki_defconfig
          else
            echo "Đang bật hook manual..."
            echo "CONFIG_KSU_MANUAL_HOOK=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> ./common/arch/arm64/configs/gki_defconfig
          fi
          echo "CONFIG_KSU_SUSFS=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> ./common/arch/arm64/configs/gki_defconfig
          if [[ "${{ github.event.inputs.lz4k_enable }}" == "true" ]]; then
            echo "CONFIG_ZSMALLOC=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_CRYPTO_LZ4HC=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_CRYPTO_LZ4K=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_CRYPTO_LZ4KD=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_CRYPTO_842=y" >> ./common/arch/arm64/configs/gki_defconfig
          fi
          # Vô hiệu hóa kiểm tra defconfig
          sed -i 's/check_defconfig//' ./common/build.config.gki
          
      - name: Thêm các thuật toán kiểm soát tắc nghẽn BBR, v.v.
        run: |
          if [[ "${{ github.event.inputs.bbr_enable }}" == "true" || "${{ github.event.inputs.bbr_enable }}" == "default" ]]; then
            echo "Đang thêm các thuật toán kiểm soát tắc nghẽn BBR..."
            cd kernel_workspace
            # Bật bộ điều khiển thuật toán kiểm soát tắc nghẽn TCP (bắt buộc)
            echo "CONFIG_TCP_CONG_ADVANCED=y" >> ./common/arch/arm64/configs/gki_defconfig
            # BBR: Thuật toán kiểm soát tắc nghẽn dựa trên dung lượng liên kết...
            echo "CONFIG_TCP_CONG_BBR=y" >> ./common/arch/arm64/configs/gki_defconfig
            # CUBIC: Thuật toán kiểm soát tắc nghẽn TCP mặc định của Android...
            echo "CONFIG_TCP_CONG_CUBIC=y" >> ./common/arch/arm64/configs/gki_defconfig
            # VEGAS: Thuật toán kiểm soát tắc nghẽn dựa trên độ trễ...
            echo "CONFIG_TCP_CONG_VEGAS=y" >> ./common/arch/arm64/configs/gki_defconfig
            # New Vegas: Phiên bản cải tiến của Vegas...
            echo "CONFIG_TCP_CONG_NV=y" >> ./common/arch/arm64/configs/gki_defconfig
            # Westwood+: Dựa trên ước lượng băng thông...
            echo "CONFIG_TCP_CONG_WESTWOOD=y" >> ./common/arch/arm64/configs/gki_defconfig
            # HTCP: Thuật toán dựa trên mất mát...
            echo "CONFIG_TCP_CONG_HTCP=y" >> ./common/arch/arm64/configs/gki_defconfig
            # Brutal: Thuật toán kiểm soát tắc nghẽn tối đa hóa thông lượng...
            echo "CONFIG_TCP_CONG_BRUTAL=y" >> ./common/arch/arm64/configs/gki_defconfig
            if [ "${{ github.event.inputs.bbr_enable }}" == "default" ]; then
              echo "Đang đặt BBR làm thuật toán kiểm soát tắc nghẽn mặc định..."
              echo "CONFIG_DEFAULT_TCP_CONG=bbr" >> ./common/arch/arm64/configs/gki_defconfig
            else
              echo "CONFIG_DEFAULT_TCP_CONG=cubic" >> ./common/arch/arm64/configs/gki_defconfig
            fi
          fi

      - name: Kích hoạt bộ lập lịch IO SSG của Samsung
        run: |
          if [[ "${{ github.event.inputs.ssg_enable }}" == "true" ]]; then
            echo "Đang kích hoạt bộ lập lịch IO SSG của Samsung…"
            cd kernel_workspace
            echo "CONFIG_MQ_IOSCHED_SSG=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_MQ_IOSCHED_SSG_CGROUP=y" >> ./common/arch/arm64/configs/gki_defconfig
          fi

      - name: Thêm tên chế tác
        run: |
          cd kernel_workspace
          echo "Thay thế hậu tố phiên bản nhân..."
          if [[ -n "${{ github.event.inputs.kernel_suffix }}" ]]; then
            echo "Hậu tố phiên bản nhân hiện tại: ${{ github.event.inputs.kernel_suffix }}"
            for f in ./common/scripts/setlocalversion; do
              sed -i "\$s|echo \"\\\$res\"|echo \"-${{ github.event.inputs.kernel_suffix }}\"|" "$f"
            done
          else
            echo "Hậu tố phiên bản nhân hiện tại: ${{ env.KERNEL_NAME }}"
            for f in ./common/scripts/setlocalversion; do
              sed -i "\$s|echo \"\\\$res\"|echo \"-${{ env.KERNEL_NAME }}\"|" "$f"
            done
          fi
           
      - name: Biên dịch nhân
        run: |
          cd kernel_workspace
          if [[ ${{ github.event.inputs.scx_enable }} == "true" ]]; then
            git clone https://github.com/cctv18/sched_ext.git
            rm -rf ./sched_ext/.git
            rm -rf ./sched_ext/README.md
            cp -r ./sched_ext/* ./common/kernel/sched
          fi
          cd common
          make -j$(nproc --all) LLVM=-20 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnuabeihf- CC=clang LD=ld.lld HOSTCC=clang HOSTLD=ld.lld O=out KCFLAGS+=-Wno-error gki_defconfig all
          echo "Biên dịch nhân hoàn tất!"

      - name: Áp dụng patch_linux và vá nhân
        run: |
          cd kernel_workspace/common/out/arch/arm64/boot
          curl -LO https://github.com/ShirkNeko/SukiSU_KernelPatch_patch/releases/download/0.12.0/patch_linux
          chmod +x patch_linux
          ./patch_linux
          rm -f Image
          mv oImage Image
          
      - name: Sao chép AnyKernel3 và đóng gói
        run: |
          cd kernel_workspace
          git clone https://github.com/cctv18/AnyKernel3 --depth=1
          rm -rf ./AnyKernel3/.git
          cd AnyKernel3
          cp ../common/out/arch/arm64/boot/Image ./Image
          if [ ! -f ./Image ]; then
            echo "Không tìm thấy file hình ảnh nhân, quá trình xây dựng có thể gặp lỗi"
            exit 1
          fi
          if [[ ${{ github.event.inputs.lz4k_enable }} == "true" ]]; then
            wget https://raw.githubusercontent.com/cctv18/oppo_oplus_realme_sm8650/refs/heads/main/zram.zip
          fi
          if [[ -n "${{ github.event.inputs.kernel_suffix }}" ]]; then
            zip -r ../AnyKernel3_SukiSU_${{ env.KSUVER }}_${{ env.KERNEL_VERSION }}_A15_${{ github.event.inputs.kernel_suffix }}.zip ./*
          else
            zip -r ../AnyKernel3_SukiSU_${{ env.KSUVER }}_${{ env.KERNEL_VERSION }}_A15_${{ env.KERNEL_NAME }}.zip ./*
          fi

      - name: Tải lên tệp ZIP
        uses: actions/upload-artifact@v4
        with:
          name: Kernel_ZIP_Artifacts # Tên tệp: Tệp ZIP Nhân
          path: ${{ github.workspace }}/kernel_workspace/*.zip

  release:
    needs: build # Yêu cầu công việc build
    runs-on: ubuntu-latest
    permissions:
      contents: write # Quyền ghi nội dung
      packages: write # Quyền ghi gói
      actions: read # Quyền đọc hành động
      
    steps:
      - name: Tải xuống tệp ZIP
        uses: actions/download-artifact@v4
        with:
          name: Kernel_ZIP_Artifacts
          path: ./release_zips

      - name: Thiết lập biến môi trường
        run: |
          if [[ -n "${{ github.event.inputs.kernel_suffix }}" ]]; then
            FULL_VERSION=${{ format('{0}.118-{1}', env.KERNEL_VERSION, github.event.inputs.kernel_suffix) }}
            echo "FULL_VERSION=$FULL_VERSION" >> $GITHUB_ENV
            export FULL_VERSION=$FULL_VERSION
          else
            FULL_VERSION=${{ format('{0}.118-{1}', env.KERNEL_VERSION, env.KERNEL_NAME) }}
            echo "FULL_VERSION=$FULL_VERSION" >> $GITHUB_ENV
            export FULL_VERSION=$FULL_VERSION
          fi
          TIME="$(TZ='Asia/Shanghai' date +'%y%m%d%H%M%S')"
          TIME_FORM="$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')"
          echo "TIME=$TIME" >> $GITHUB_ENV
          echo "TIME_FORM=$TIME_FORM" >> $GITHUB_ENV
          TAG_HEAD="OPPO+OPlus+Realme-A15-build"
          echo "TAG_HEAD=$TAG_HEAD" >> $GITHUB_ENV
         
      - name: Tạo bản phát hành
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ env.TAG_HEAD }}-${{ env.TIME }}"
          name: "${{ env.TAG_HEAD }}-${{ env.FULL_VERSION }}"
          body: |
            ### 📱 Nhân Chung Âu Gia Chân Android 15 SukiSU-Ultra SM8650 | Thông tin xây dựng
            - Phiên bản nhân: ${{ env.FULL_VERSION }}
            - Thời gian biên dịch: ${{ env.TIME_FORM }}
            - Mẫu máy: Nhân chung Android 15 Snapdragon 8Gen3 Âu Gia Chân (dựa trên mã nguồn OKI chính thức của OnePlus 12 Android 15)
            - Tính năng: SukiSU Ultra + SUSFS + VFS + KPM
            - Chế độ hook: ${{ github.event.inputs.hook_method }}
            - Hỗ trợ LZ4KD: ${{ github.event.inputs.lz4k_enable }}
            - Hỗ trợ LZ4: ${{ github.event.inputs.lz4_enable }}
            - Hỗ trợ thuật toán kiểm soát tắc nghẽn BBR/Brutal: ${{ github.event.inputs.bbr_enable }}
            - Hỗ trợ bộ lập lịch IO SSG của Samsung: ${{ github.event.inputs.ssg_enable }}
            - Hỗ trợ nhân Fengchi: ${{ github.event.inputs.scx_enable }}
            - Hệ thống đề xuất: ColorOS 15 / RealmeUI 6.0
            - Tải xuống trình quản lý SukiSU: [SukiSU-Ultra](https://github.com/ShirkNeko/SukiSU-Ultra/releases)
            ### ⏫️ Nội dung cập nhật:
            - Cập nhật SukiSU Ultra lên phiên bản mới nhất (${{ needs.build.outputs.ksuver }})
            - (Dự phòng)
            ### 📋 Hướng dẫn cài đặt
            1. Nếu điện thoại đã cài Recovery bên thứ ba (như TWRP), tải gói AnyKernel tương ứng với mẫu máy, vào chế độ Recovery, flash gói AnyKernel và khởi động lại thiết bị.
            2. Nếu điện thoại đã có quyền root, cài đặt [HorizonKernelFlasher](https://github.com/libxzr/HorizonKernelFlasher/releases), flash gói AnyKernel trong HorizonKernelFlasher và khởi động lại.
            3. Nếu đã flash nhân SukiSU Ultra và trình quản lý SukiSU Ultra đã được cập nhật lên phiên bản mới nhất, flash gói AnyKernel trực tiếp trong trình quản lý SukiSU Ultra và khởi động lại.
            4. Trước khi flash nhân không có bản vá LZ4KD, nếu đã flash phiên bản có bản vá LZ4KD, hãy tắt mô-đun zram để tránh lỗi.
            #### ※※※ Flash nhân có rủi ro, để tránh trường hợp thiết bị bị brick, hãy sử dụng [KernelFlasher](https://github.com/capntrips/KernelFlasher) để sao lưu các phân vùng khởi động quan trọng như boot trước khi flash!※※※
          draft: false # Không phải bản nháp
          prerelease: false # Không phải bản phát hành trước
          files: |
            release_zips/AnyKernel3_*.zip